version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4111:4111"
    environment:
      - NODE_ENV=production
      - PORT=4111
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.mastra/mastra.db:/app/.mastra/mastra.db
    restart: unless-stopped
