app = "what-would-vimes-do-api"
primary_region = "lhr"

[build]

[env]
PORT = "4111"

[http_service]
  internal_port = 4111
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  handlers = ["http"]
  port = 80

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443
